schema_version = "1.0.0"

id = "area_lights_from_faces"
version = "1.2.1"
name = "Area Lights From Faces"
tagline = "Creates Area Lights From Selected Faces"
maintainer = "Anthony Aragues <https://blendermarket.com/products/area-lights>"
type = "add-on"
tags = ["Lighting"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-2.0-or-later",
]